# 统计与大数据分析软件第十次作业

## 第一题

创建并储存三维数组，该数组有6层，每层是4*2阶矩阵，并以适当的步长按降序将4.8-0.1填充到数组中。

然后按照顺序提取所有层的第二列第四行和第一行的所有元素，并存储为一个新的对象。

In [1]:
# 创建降序向量，从 4.8 到 0.1，步长适当
values <- round(seq(4.8, 0.1, by = -0.1), 1)

In [2]:
# 检查长度是否符合 6 层 * 4 行 * 2 列 = 48
length(values)  # 应该是 48

[1] 48

In [3]:
# 创建三维数组：维度为 4x2x6
arr <- array(values, dim = c(4, 2, 6))
print(arr)  # 把“层”放到第一维

, , 1

     [,1] [,2]
[1,]  4.8  4.4
[2,]  4.7  4.3
[3,]  4.6  4.2
[4,]  4.5  4.1

, , 2

     [,1] [,2]
[1,]  4.0  3.6
[2,]  3.9  3.5
[3,]  3.8  3.4
[4,]  3.7  3.3

, , 3

     [,1] [,2]
[1,]  3.2  2.8
[2,]  3.1  2.7
[3,]  3.0  2.6
[4,]  2.9  2.5

, , 4

     [,1] [,2]
[1,]  2.4  2.0
[2,]  2.3  1.9
[3,]  2.2  1.8
[4,]  2.1  1.7

, , 5

     [,1] [,2]
[1,]  1.6  1.2
[2,]  1.5  1.1
[3,]  1.4  1.0
[4,]  1.3  0.9

, , 6

     [,1] [,2]
[1,]  0.8  0.4
[2,]  0.7  0.3
[3,]  0.6  0.2
[4,]  0.5  0.1



In [4]:
# 初始化结果矩阵，每行对应一层，共6行
# 每行包括：row4_col2、row1_col1、row1_col2

result <- matrix(nrow = 6, ncol = 3)

In [5]:
colnames(result) <- c("row4_col2", "row1_col1", "row1_col2")
colnames(result)  # 设置列名

[1] "row4_col2" "row1_col1" "row1_col2"

In [6]:
for (i in 1:6) {
  row4_col2 <- arr[4, 2, i]
  row1_col1 <- arr[1, 1, i]
  row1_col2 <- arr[1, 2, i]
  result[i, ] <- c(row4_col2, row1_col1, row1_col2)
}

In [7]:
# 查看结果（可选）
result

row4_col2 row1_col1 row1_col2
[1,] 4.1       4.8       4.4      
[2,] 3.3       4.0       3.6      
[3,] 2.5       3.2       2.8      
[4,] 1.7       2.4       2.0      
[5,] 0.9       1.6       1.2      
[6,] 0.1       0.8       0.4

## 第二题

### （1）

Store the following vector of 15 values as an object in your workspace: c(6,9,7,3,6,7,9,6,3,6,6,7,1,9,1). Identify the following elements:

1. Those equal to 6
2. Those greater than or equal to 6
3. Those less than 6 + 2
4. Those not equal to 6

In [8]:
vec <- c(6,9,7,3,6,7,9,6,3,6,6,7,1,9,1)

In [9]:
eq_6 <- vec[vec == 6]
eq_6.index <- which(vec == 6)
eq_6.index

[1]  1  5  8 10 11

In [10]:
ge_6 <- vec[vec >= 6]
ge_6.index <- which(vec >= 6)
ge_6.index

[1]  1  2  3  5  6  7  8 10 11 12 14

In [11]:
lt_6 <- vec[vec < 6+2]
lt_6.index <- which(vec < 6+2)
lt_6.index

[1]  1  3  4  5  6  8  9 10 11 12 13 15

In [12]:
ne_6 <- vec[vec != 6]
ne_6.index <- which(vec != 6)
ne_6.index

[1]  2  3  4  6  7  9 12 13 14 15

### （2）

 Create a new vector from the one used in 3(a) by deleting its first three elements. With this new vector, fill a 2 * 2 * 3 array. Examine the array for the following entries:

1. Those less than or equal to 6 divided by 2, plus 4
2. Those less than or equal to 6 divided by 2, plus 4, after increasing every element in the array by 2

In [13]:
new_vec <- vec[-c(1, 2, 3)]  # 或 new_vec <- vec[4:15]
new_vec

[1] 3 6 7 9 6 3 6 6 7 1 9 1

我们改变维度，将向量变成矩阵

In [14]:
arr <- array(new_vec, dim = c(2, 2, 3))
print(arr)

, , 1

     [,1] [,2]
[1,]    3    7
[2,]    6    9

, , 2

     [,1] [,2]
[1,]    6    6
[2,]    3    6

, , 3

     [,1] [,2]
[1,]    7    9
[2,]    1    1



In [15]:
# i. 筛选 <= 6/2 + 4 的元素
logical_array1 <- arr <= (6 / 2 + 4)
arr[logical_array1]  # 筛选出的元素
logical_array1.index <- which(logical_array1, arr.ind = TRUE)  # 筛选出的元素的索引
logical_array1.index  # 筛选出的元素的索引

[1] 3 6 7 6 3 6 6 7 1 1

dim1 dim2 dim3
 [1,] 1    1    1   
 [2,] 2    1    1   
 [3,] 1    2    1   
 [4,] 1    1    2   
 [5,] 2    1    2   
 [6,] 1    2    2   
 [7,] 2    2    2   
 [8,] 1    1    3   
 [9,] 2    1    3   
[10,] 2    2    3

In [16]:
# ii. 先将数组每个元素 +2，再筛选 <= 6/2 + 4 的元素
arr_plus2 <- arr + 2
arr_plus2  # 打印加2后的数组
new_array2 <- arr_plus2[arr_plus2 <= (6 / 2 + 4)]
print(new_array2)  # 打印筛选出的元素
new_array2.index <- which(arr_plus2 <= (6 / 2 + 4), arr.ind = TRUE)  # 筛选出的元素的索引
print(new_array2.index)  # 打印筛选出的元素的索引

, , 1

     [,1] [,2]
[1,]    5    9
[2,]    8   11

, , 2

     [,1] [,2]
[1,]    8    8
[2,]    5    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]    3    3

[1] 5 5 3 3
     dim1 dim2 dim3
[1,]    1    1    1
[2,]    2    1    2
[3,]    2    1    3
[4,]    2    2    3


In [17]:
logical_array2 <- arr_plus2 <= (6 / 2 + 4)  # 逻辑数组
print(logical_array2)  # 打印逻辑数组

, , 1

      [,1]  [,2]
[1,]  TRUE FALSE
[2,] FALSE FALSE

, , 2

      [,1]  [,2]
[1,] FALSE FALSE
[2,]  TRUE FALSE

, , 3

      [,1]  [,2]
[1,] FALSE FALSE
[2,]  TRUE  TRUE



### （3）

Check whether any of the values of the logical arrays created in 3(b) are TRUE. If they are, check whether they are all TRUE.

In [18]:
# 检查 logical_array1 中是否有 TRUE
any_true1 <- any(logical_array1)
all_true1 <- all(logical_array1)

print(any_true1)  # 打印是否有 TRUE
print(all_true1)  # 打印是否全部为 TRUE

[1] TRUE
[1] FALSE


In [19]:
# 检查 logical_array2 中是否有 TRUE
any_true2 <- any(logical_array2)
all_true2 <- all(logical_array2)

print(any_true2)  # 打印是否有 TRUE
print(all_true2)  # 打印是否所有元素都是 TRUE

[1] TRUE
[1] FALSE


## 第三题

### （1）

Store this vector of 10 values: foo <- c(7,5,6,1,2,10,8,3,8,2). Then, do the following:

1. Extract the elements greater than or equal to 5, storing the result as bar.
2. Display the vector containing those elements from foo that remain after omitting all elements that are greater than or equal to 5.

对于第一问，首先定义向量 foo：

In [20]:
foo <- c(7,5,6,1,2,10,8,3,8,2)
foo

[1]  7  5  6  1  2 10  8  3  8  2

(i) 提取 foo 中 ≥5 的元素，赋值给 bar

In [21]:
bar <- foo[ foo >= 5 ]
bar
bar.index <- which(foo >= 5)
bar.index

[1]  7  5  6 10  8  8

[1] 1 2 3 6 7 9

(ii) 提取 foo 中 <5 的元素

In [22]:
foo_lt5 <- foo[ foo < 5 ]
foo_lt5
foo_lt5.index <- which(foo < 5)
foo_lt5.index

[1] 1 2 3 2

[1]  4  5  8 10

### （2）

Use bar from 4(a)(i) to construct a 2*3 matrix called baz, filling in a row-wise fashion. Then, do the following:

1. Replace any elements that are equal to 8 with the squared value of the element in row 1, column 2 of baz itself.
2. Confirm that all values in baz are now less than or equal to 25 and greater than 4.

用 bar 构造 2×3 的矩阵 baz（按行填充）

In [23]:
baz <- matrix(bar, nrow = 2, ncol = 3, byrow = TRUE)
baz


[,1] [,2] [,3]
[1,]  7   5    6   
[2,] 10   8    8

(i) 将所有等于 8 的元素替换为 baz[1,2]^2（即 5^2 = 25）

In [24]:
baz[ baz == 8 ] <- baz[1,2]^2
baz

[,1] [,2] [,3]
[1,]  7    5    6  
[2,] 10   25   25

(ii) 检查 baz 中是否所有值都 ≤25 且 >4

In [25]:
all(baz <= 25 & baz > 4)

[1] TRUE