# 统计与大数据分析软件第十三次作业

## 第一题

Write R code that takes a square character matrix and checks if any of the character strings on the diagonal (top left to bottom right) begin with the letter g, lowercase or uppercase. 

If satisfied, these specific entries should be overwritten with the string "HERE". 

Otherwise, the entire matrix should be replaced with an identity matrix of the same dimensions. 

try your code on the following matrices, checking the result each time:

这道题需要我们设计一个函数，检查方阵对角线上的值是否以g/G开头，代码如下：

In [1]:
# 定义函数处理矩阵
process_matrix <- function(mat) {
  # 获取矩阵维度
  n <- nrow(mat)
  # 检查对角线元素是否有以g开头的
  diag_elements <- diag(mat)
  has_g <- any(grepl("^[gG]", diag_elements))
  
  if (has_g) {
    # 替换以g开头的对角线元素为"HERE"
    for (i in 1:n) {
      if (grepl("^[gG]", mat[i, i])) {
        mat[i, i] <- "HERE"
      }
    }
  } else {
    # 否则替换为单位矩阵
    mat <- diag(n)
  }
  return(mat)
}


1. mymat <- matrix(as.character(1:16),4,4)


In [2]:
# 测试矩阵i
mymat <- matrix(as.character(1:16), 4, 4)
print(process_matrix(mymat))

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1


2. mymat <- matrix(c("DANDELION","Hyacinthus","Gerbera","MARIGOLD", "geranium","ligularia","Pachysandra","SNAPDRAGON","GLADIOLUS"),3,3)

In [3]:
# 测试矩阵ii
mymat <- matrix(c("DANDELION", "Hyacinthus", "Gerbera", "MARIGOLD", 
                 "geranium", "ligularia", "Pachysandra", "SNAPDRAGON", 
                 "GLADIOLUS"), 3, 3)
print(process_matrix(mymat))

     [,1]         [,2]        [,3]         
[1,] "DANDELION"  "MARIGOLD"  "Pachysandra"
[2,] "Hyacinthus" "HERE"      "SNAPDRAGON" 
[3,] "Gerbera"    "ligularia" "HERE"       



3. mymat <- matrix(c("GREAT","exercises","right","here"),2,2,byrow=T)

In [4]:
# 测试矩阵iii
mymat <- matrix(c("GREAT", "exercises", "right", "here"), 2, 2, byrow = TRUE)
print(process_matrix(mymat))

     [,1]    [,2]       
[1,] "HERE"  "exercises"
[2,] "right" "here"     


## 第二题

 Assume the object mynum will only ever be a single integer between 0 and 9. 
 
 Use ifelse and switch to produce a command that takes in mynum and returns a matching character string for all possible values 0, 1, ... , 9. 
 
 Supplied with 3, for example, it should return "three"; supplied with 0, it should return "zero".

这道题要求我们使用`ifelse`和`switch`结合，实现输入1位数字返回单词的功能：

In [5]:
int_to_word <- function(mynum) {
  mynum_str <- as.character(mynum)
  if (mynum_str == "0") {
    return("zero")
  } else if (mynum_str == "1") {
    return("one")
  } else if (mynum_str == "2") {
    return("two")
  } else if (mynum_str == "3") {
    return("three")
  } else if (mynum_str == "4") {
    return("four")
  } else if (mynum_str == "5") {
    return("five")
  } else if (mynum_str == "6") {
    return("six")
  } else if (mynum_str == "7") {
    return("seven")
  } else if (mynum_str == "8") {
    return("eight")
  } else if (mynum_str == "9") {
    return("nine")
  } else {
    return("未知数字")
  }
}


或者采用下面的方式：

In [6]:
# 使用ifelse和switch将整数转换为对应的英文单词
int_to_word <- function(mynum) {
  switch(as.character(mynum),
         "0" = "zero",
         "1" = "one",
         "2" = "two",
         "3" = "three",
         "4" = "four",
         "5" = "five",
         "6" = "six",
         "7" = "seven",
         "8" = "eight",
         "9" = "nine",
         "未知数字")
}

In [7]:
# 获取用户输入并转换为英文单词
user_input_str <- readline(prompt="请输入一个0到9之间的数字: ")
user_input_num <- as.integer(user_input_str)

# 检查输入是否有效（可选，但建议）
if (!is.na(user_input_num) && user_input_num >= 0 && user_input_num <= 9) {
  result_word <- int_to_word(user_input_num)
  cat("您输入的数字对应的英文是:", result_word, "\n")
} else {
  cat("输入无效，请输入一个0到9之间的整数。\n")
}

您输入的数字对应的英文是: four 


## 第三题

We used the command switch(EXPR=mystring,Homer=12,Marge=34,Bart=56,Lisa=78,Maggie=90, NA) to return a number based on the supplied value of a single character string. 

This line won’t work if mystring is a character vector. 

Write some code that will take a character vector and return a vector of the appropriate numeric values. 

这道题要求我们拓展`switch`函数，实现字符串向量的处理。

In [8]:
# 定义字符到数值的映射函数
char_to_num <- function(char_vec) {
  # 定义映射表
  mapping <- list(
    "Homer" = 12,
    "Marge" = 34,
    "Bart" = 56,
    "Lisa" = 78,
    "Maggie" = 90
  )
  
  # 对每个元素应用映射
  result <- sapply(char_vec, function(x) {
    if (x %in% names(mapping)) {
      mapping[[x]]
    } else {
      NA
    }
  })
  
  return(result)
}


Test it on the following vector:

c("Peter","Homer","Lois","Stewie","Maggie","Bart")

In [9]:
# 测试函数
test_vector <- c("Peter", "Homer", "Lois", "Stewie", "Maggie", "Bart")
print(char_to_num(test_vector))

 Peter  Homer   Lois Stewie Maggie   Bart 
    NA     12     NA     NA     90     56 


## 第四题

Convert the following for loop to an implicit loop that does exactly the same thing:

将以下for循环转换为隐式循环，以实现完全相同的功能：

In [10]:
matlist <- list(
    matrix(c(T,F,T,T),2,2),
    matrix(c("a","c","b","z","p","q"),3,2),
    matrix(1:8,2,4)
)
print(matlist)

[[1]]
      [,1] [,2]
[1,]  TRUE TRUE
[2,] FALSE TRUE

[[2]]
     [,1] [,2]
[1,] "a"  "z" 
[2,] "c"  "p" 
[3,] "b"  "q" 

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8



In [11]:
for(i in 1:length(matlist)){
    matlist[[i]] <- t(matlist[[i]])
}
print(matlist)

[[1]]
     [,1]  [,2]
[1,] TRUE FALSE
[2,] TRUE  TRUE

[[2]]
     [,1] [,2] [,3]
[1,] "a"  "c"  "b" 
[2,] "z"  "p"  "q" 

[[3]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8



但是按照题意，我们要把for循环转变为隐式循环：

In [12]:
matlist0 <- list(
    matrix(c(T,F,T,T),2,2),
    matrix(c("a","c","b","z","p","q"),3,2),
    matrix(1:8,2,4)
)
print(matlist0)

[[1]]
      [,1] [,2]
[1,]  TRUE TRUE
[2,] FALSE TRUE

[[2]]
     [,1] [,2]
[1,] "a"  "z" 
[2,] "c"  "p" 
[3,] "b"  "q" 

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8



In [13]:
# 使用lapply进行隐式循环
matlist0 <- lapply(matlist0, t)

# 打印结果
print(matlist0)

[[1]]
     [,1]  [,2]
[1,] TRUE FALSE
[2,] TRUE  TRUE

[[2]]
     [,1] [,2] [,3]
[1,] "a"  "c"  "b" 
[2,] "z"  "p"  "q" 

[[3]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8



## 第五题

Write a recursive version of a function implementing the nonnegative integer factorial operator. 

The stopping rule should return the value 1 if the supplied integer is 0. 

Confirm that your function produces the same results as earlier.

我们需要使用递归写一个函数计算阶乘：

In [14]:
# 递归实现阶乘函数
factorial_recursive <- function(n) {
  # 基本情况：0的阶乘是1
  if (n == 0) {
    return(1)
  } else {
    # 递归情况：n的阶乘是n乘以(n-1)的阶乘
    return(n * factorial_recursive(n - 1))
  }
}

后面你会发现，这样计算的时候会出现大数无法计算的情况。我们需要重新调整：

In [15]:
# 安装并加载Rmpfr包（如果尚未安装）
if (!requireNamespace("Rmpfr", quietly = TRUE)) {
  install.packages("Rmpfr")
}
library(Rmpfr)

Warning message:
"package 'Rmpfr' was built under R version 4.4.3"
Loading required package: gmp

Warning message:
"package 'gmp' was built under R version 4.4.3"

Attaching package: 'gmp'


The following objects are masked from 'package:base':

    %*%, apply, crossprod, matrix, tcrossprod


C code of R package 'Rmpfr': GMP using 64 bits per limb



Attaching package: 'Rmpfr'


The following object is masked from 'package:gmp':

    outer


The following objects are masked from 'package:stats':

    dbinom, dgamma, dnbinom, dnorm, dpois, dt, pgamma, pnorm


The following objects are masked from 'package:base':

    cbind, pmax, pmin, rbind




In [16]:
# 递归实现高精度阶乘函数
factorial_recursive_high <- function(n) {
  # 基本情况：0的阶乘是1
  if (n == 0) {
    return(mpfr(1, precBits = 128))  # 使用高精度数值
  } else {
    # 递归情况：n的阶乘是n乘以(n-1)的阶乘
    return(n * factorial_recursive_high(n - 1))
  }
}

1. 5 factorial is 120.

In [17]:
print(factorial_recursive(5))  # 应返回120
print(factorial_recursive_high(5))  # 应返回120

[1] 120
1 'mpfr' number of precision  256   bits 
[1] 120


2. 120 factorial is 479;001;600.

In [18]:
print(factorial_recursive(12))  # 应返回479001600
print(factorial_recursive_high(12))  # 应返回479001600

[1] 479001600
1 'mpfr' number of precision  256   bits 
[1] 479001600


3. 0 factorial is 1.

In [19]:
print(factorial_recursive(0))  # 应返回1
print(factorial_recursive_high(0))  # 应返回1


[1] 1
1 'mpfr' number of precision  256   bits 
[1] 1
